query ($projectId: ID!, $memberId: ID!, $sort: MessagedSort) {
  projects(where: { id: $projectId }) {
    members(where: { id: $memberId }) {
      messagedWithConnection(sort: { edge: $sort }) {
        edges {
          activityCount
          activities
          conversations
          conversationCount
          lastInteractedAt
          node {
            globalActor
            globalActorName
          }
        }
      }
    }
  }
}
