#import "src/graphql/fragments/ActivityFields.gql"
fragment ForActivityFeed on Activity {
  ...ActivityFields
  conversation {
    ...ActivityFields
    descendants(options: { sort: { timestampInt: ASC } }) {
      ...ActivityFields
      parent {
        id
      }
    }
  }
}
