#import "src/graphql/fragments/ForActivityFeed.gql"
fragment MemberActivitiesConnection on MemberActivitiesConnection {
  edges {
    node {
      ...ForActivityFeed
    }
  }
  pageInfo {
    hasNextPage
  }
}
