#import "src/graphql/fragments/ForActivityFeed.gql"
fragment ProjectActivitiesConnection on ProjectActivitiesConnection {
  edges {
    node {
      ...ForActivityFeed
    }
  }
  pageInfo {
    hasNextPage
  }
}
