import { library } from "@fortawesome/fontawesome-svg-core";
import {
  faChevronDown,
  faChevronUp,
  faChevronLeft,
  faArrowsSpin,
  faArrowDown,
  faArrowLeft,
  faArrowRight,
  faShuffle,
  faExpand,
  faSquare,
  faSort,
  faKeyboard,
  faRightLeft,
  faGear,
  faSearch,
  faCircleNotch,
  faCircleNodes,
  faReply,
  faTag,
  faUser,
  faList,
  faBars,
  faXmark,
  faCircle,
  faBrush,
  faHeart,
  faTowerBroadcast,
  faUserAstronaut,
  faComment,
  faArrowsRotate,
  faWandMagicSparkles,
  faPaperPlane,
  faBookmark,
  faArrowUpRightFromSquare,
  faRobot,
  faLocationPin,
  faFileCode,
  faFilter,
} from "@fortawesome/free-solid-svg-icons";

import { faBookmark as faBookmarkRegular } from "@fortawesome/free-regular-svg-icons";

import {
  faTwitter,
  faDiscord,
  faGithub,
  faDiscourse,
  faSlack,
} from "@fortawesome/free-brands-svg-icons";

// add to library
library.add(
  faArrowsSpin,
  faChevronDown,
  faChevronUp,
  faShuffle,
  faExpand,
  faArrowDown,
  faSquare,
  faSort,
  faChevronLeft,
  faKeyboard,
  faArrowLeft,
  faArrowRight,
  faRightLeft,
  faTwitter,
  faDiscord,
  faSlack,
  faGithub,
  faDiscourse,
  faGear,
  faSearch,
  faCircleNotch,
  faReply,
  faTag,
  faUser,
  faList,
  faBrush,
  faBars,
  faXmark,
  faCircle,
  faHeart,
  faTowerBroadcast,
  faUserAstronaut,
  faCircleNodes,
  faHeart,
  faComment,
  faArrowsRotate,
  faWandMagicSparkles,
  faPaperPlane,
  faBookmark,
  faBookmarkRegular,
  faArrowUpRightFromSquare,
  faRobot,
  faLocationPin,
  faFileCode,
  faFilter
);

export default library;

import "@fortawesome/fontawesome-svg-core/styles.css";
