import { library } from "@fortawesome/fontawesome-svg-core";
import {
  faYinYang,
  faHeartCircleCheck,
  faBuildingColumns,
  faLightbulb,
  faChevronDown,
  faChevronUp,
  faChevronLeft,
  faArrowsSpin,
  faArrowDown,
  faArrowLeft,
  faArrowRight,
  faShuffle,
  faExpand,
  faSquare,
  faSort,
  faKeyboard,
  faRightLeft,
  faGear,
  faSearch,
  faCircleNotch,
  faReply,
  faTag,
  faUser,
  faList,
} from "@fortawesome/free-solid-svg-icons";

import {
  faTwitter,
  faDiscord,
  faGithub,
  faDiscourse,
} from "@fortawesome/free-brands-svg-icons";

import {
  faBars,
  faXmark,
  faSolarSystem,
  faPlanetMoon,
  faPlanetRinged,
  faRocketLaunch,
  faCircleNodes,
  faFaceSadCry,
  faTrafficCone,
  faDrawCircle,
  faChartNetwork,
  faChartMixed,
  faTire,
  faBoxCheck,
  faStairs,
  faPause,
  faPlay,
  faCircle1,
  faCircle2,
  faCircle3,
  faCircle4,
  faUserAstronaut,
  faHeart,
  faSignalStream,
  faCircle,
  faQuestion,
  faNote,
  faMessages,
} from "@fortawesome/pro-solid-svg-icons";

import { faTelescope } from "@fortawesome/pro-duotone-svg-icons";

// add to library
library.add(
  faBars,
  faXmark,
  faYinYang,
  faSolarSystem,
  faPlanetRinged,
  faPlanetMoon,
  faRocketLaunch,
  faCircleNodes,
  faHeartCircleCheck,
  faTrafficCone,
  faFaceSadCry,
  faDrawCircle,
  faChartNetwork,
  faChartMixed,
  faBuildingColumns,
  faTire,
  faBoxCheck,
  faStairs,
  faPause,
  faPlay,
  faCircle1,
  faCircle2,
  faCircle3,
  faCircle4,
  faUserAstronaut,
  faHeart,
  faSignalStream,
  faLightbulb,
  faCircle,
  faArrowsSpin,
  faChevronDown,
  faChevronUp,
  faShuffle,
  faExpand,
  faArrowDown,
  faSquare,
  faQuestion,
  faSort,
  faChevronLeft,
  faKeyboard,
  faArrowLeft,
  faArrowRight,
  faRightLeft,
  faTelescope,
  faTwitter,
  faDiscord,
  faGithub,
  faDiscourse,
  faGear,
  faSearch,
  faNote,
  faMessages,
  faCircleNotch,
  faReply,
  faTag,
  faUser,
  faList
);

export default library;

import "@fortawesome/fontawesome-svg-core/styles.css";
