#import "src/graphql/fragments/ProjectActivitiesConnection.gql"
query (
  $projectId: ID!
  $first: Int!
  $after: String
  $where: ProjectActivitiesConnectionWhere
) {
  projects(where: { id: $projectId }) {
    activitiesConnection(
      first: $first
      after: $after
      where: $where
      sort: { node: { timestamp: DESC } }
    ) {
      ...ProjectActivitiesConnection
    }
  }
}
