#import "src/graphql/fragments/ActivityFields.gql"
query ($projectId: ID!, $first: Int!, $after: String!) {
  projects(where: { id: $projectId }) {
    activitiesConnection(
      first: $first
      after: $after
      sort: { node: { timestamp: DESC } }
    ) {
      edges {
        node {
          ...ActivityFields
          conversation {
            ...ActivityFields
            descendants {
              ...ActivityFields
              parent {
                id
              }
            }
          }
        }
      }
    }
  }
}
