query ($projectId: ID!, $first: Int!, $after: String) {
  projects(where: { id: $projectId }) {
    membersConnection(first: $first, after: $after) {
      edges {
        node {
          globalActor
          globalActorName
          activitiesAggregate {
            count
          }
        }
      }
      pageInfo {
        hasNextPage
      }
      totalCount
    }
  }
}
