query ($projectId: ID!, $first: Int!, $after: String, $sort: MemberSort) {
  projects(where: { id: $projectId }) {
    membersConnection(first: $first, after: $after, sort: { node: $sort }) {
      edges {
        node {
          id
          globalActor
          globalActorName
          activitiesAggregate {
            count
          }
          messagedWithConnection {
            totalCount
          }
        }
      }
      pageInfo {
        hasNextPage
      }
      totalCount
    }
  }
}
