#import "src/graphql/fragments/MemberActivitiesConnection.gql"
query ($projectId: ID!, $memberId: ID!, $first: Int!, $after: String!) {
  projects(where: { id: $projectId }) {
    members(where: { id: $memberId }) {
      activitiesConnection(
        first: $first
        after: $after
        sort: { node: { timestampInt: DESC } }
      ) {
        ...MemberActivitiesConnection
      }
    }
  }
}
