#import "src/graphql/fragments/ForConversationFeed.gql"
query ($projectId: ID!) {
  users {
    bookmarksConnection(
      sort: { edge: { createdAtInt: DESC } }
      where: { node: { project: { id: $projectId } } }
    ) {
      edges {
        createdAt
        createdAtInt
        node {
          id
          ...ForConversationFeed
        }
      }
    }
  }
}
