query ($projectId: ID!, $propertyNames: [String], $source: String) {
  projects(where: { id: $projectId }) {
    propertyFilters(propertyNames: $propertyNames, source: $source) {
      name
      values {
        value
        count
      }
    }
  }
}
