#import "src/graphql/fragments/ActivityFields.gql"
#import "src/graphql/fragments/ConversationFields.gql"
query ($projectId: ID!, $ids: [ID!]) {
  projects(where: { id: $projectId }) {
    activities(where: { id_IN: $ids }) {
      ...ActivityFields
      conversation {
        ...ConversationFields
      }
    }
  }
}
