query ($projectId: ID!, $memberId: ID!, $connectionId: ID!) {
  projects(where: { id: $projectId }) {
    members(where: { id: $memberId }) {
      messagedWithConnection(where: { node: { id: $connectionId } }) {
        edges {
          activityCount
          conversationIds
          conversationCount
          lastInteractedAt
        }
      }
    }
  }
}
